#!/usr/bin/env python3
"""Create a set of demo Git repositories for the dashboard (offline, deterministic).

The generated repositories deliberately cover every state the dashboard reports:

======  ==========================  ==========================================
Name    State                       Purpose
======  ==========================  ==========================================
atlas-api          active, 4 branches  normal busy repository
nebula-web         active, 2 authors   second active repository
legacy-billing     stale (≈140 days)   stale repository with stale branches
side-experiment    abandoned (≈400 d)  abandoned candidate
infra-scripts      dirty working tree  uncommitted/staged/untracked detection
detached-sandbox   detached HEAD       detached HEAD warning
empty-project      no commits          "repository has no commits yet"
mirror.git         bare                bare repository handling
======  ==========================  ==========================================

Usage::

    python scripts/create_demo_repos.py [--target data/demo] [--repos 8] [--seed 1337]

Requires a working Git installation. Uses no network access.
"""

from __future__ import annotations

import argparse
import os
import random
import subprocess
import sys
from datetime import datetime, timedelta, timezone
from pathlib import Path

AUTHORS = [
    ("Ada Lovelace", "ada@example.com"),
    ("Grace Hopper", "grace@example.com"),
    ("Linus Torvalds", "linus@example.com"),
    ("Margaret Hamilton", "margaret@example.com"),
]

MODULES = ["api", "billing", "cache", "config", "database", "events", "handlers", "models", "router", "services", "utils", "worker"]
VERBS = ["add", "fix", "refactor", "document", "optimise", "harden", "extract", "rename", "test"]
SUBJECTS = [
    "handle empty payloads",
    "avoid duplicate lookups",
    "drop unused dependency",
    "support retry with backoff",
    "guard against missing config",
    "speed up the aggregation query",
    "clarify error messages",
    "cover the edge case in tests",
]


def git(repo: Path, *args: str, env: dict[str, str] | None = None, check: bool = True) -> subprocess.CompletedProcess:
    environment = dict(os.environ)
    environment.update(
        {
            "GIT_AUTHOR_NAME": "Demo Bot",
            "GIT_AUTHOR_EMAIL": "demo@example.com",
            "GIT_COMMITTER_NAME": "Demo Bot",
            "GIT_COMMITTER_EMAIL": "demo@example.com",
            "GIT_CONFIG_GLOBAL": "/dev/null",
            "GIT_CONFIG_SYSTEM": "/dev/null",
        }
    )
    if env:
        environment.update(env)
    result = subprocess.run(
        ["git", *args],
        cwd=str(repo),
        env=environment,
        capture_output=True,
        text=True,
        check=False,
    )
    if check and result.returncode != 0:
        raise RuntimeError(f"git {' '.join(args)} failed in {repo}: {result.stderr.strip()}")
    return result


def init_repo(path: Path, *, bare: bool = False) -> None:
    path.mkdir(parents=True, exist_ok=True)
    if bare:
        git(path, "init", "--bare")
    else:
        git(path, "init", "-b", "main")
    git(path, "config", "user.name", "Demo Bot")
    git(path, "config", "user.email", "demo@example.com")


def write_file(repo: Path, relative: str, content: str) -> None:
    target = repo / relative
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content, encoding="utf-8")


def commit(repo: Path, message: str, when: datetime, author: tuple[str, str]) -> None:
    stamp = when.astimezone(timezone.utc).strftime("%Y-%m-%dT%H:%M:%S+00:00")
    git(repo, "add", "-A")
    git(
        repo,
        "commit",
        "-m",
        message,
        env={
            "GIT_AUTHOR_DATE": stamp,
            "GIT_COMMITTER_DATE": stamp,
            "GIT_AUTHOR_NAME": author[0],
            "GIT_AUTHOR_EMAIL": author[1],
            "GIT_COMMITTER_NAME": author[0],
            "GIT_COMMITTER_EMAIL": author[1],
        },
    )


def random_message(rng: random.Random) -> str:
    return f"{rng.choice(VERBS)} {rng.choice(MODULES)}: {rng.choice(SUBJECTS)}"


def build_history(repo: Path, *, commits: int, start: datetime, last: datetime, rng: random.Random) -> Path:
    """Create ``commits`` commits spread between ``start`` and ``last``."""
    readme = f"# {repo.name}\n\nDemo repository generated by scripts/create_demo_repos.py\n"
    write_file(repo, "README.md", readme)
    if commits:
        span = max((last - start).total_seconds(), 1)
        for index in range(commits):
            when = start + timedelta(seconds=(span / commits) * index + rng.randint(0, 3600))
            when = min(when, last)
            module = rng.choice(MODULES)
            lines = [f"# {module} module", "", f"iteration = {index}"]
            lines += [f"def function_{line}():\n    return {line}\n" for line in range(rng.randint(1, 4))]
            write_file(repo, f"src/{module}.py", "\n".join(lines) + "\n")
            if index % 5 == 0:
                write_file(repo, f"tests/test_{module}.py", f"def test_{module}():\n    assert {index} == {index}\n")
            author = AUTHORS[index % len(AUTHORS)] if commits > 20 else AUTHORS[0]
            commit(repo, random_message(rng), when, author)
    return repo


def demo_repositories(target: Path, *, count: int, seed: int) -> list[Path]:
    rng = random.Random(seed)
    now = datetime.now(timezone.utc).replace(microsecond=0)
    target.mkdir(parents=True, exist_ok=True)
    created: list[Path] = []

    def prepare(name: str) -> Path | None:
        """Create an empty repository unless it already exists."""
        path = target / name
        if path.exists():
            print(f"  · {path} already exists, skipping")
            return None
        init_repo(path)
        return path

    # 1. busy repository, four branches, three stale feature branches
    atlas = prepare("atlas-api")
    if atlas is None:
        return created
    build_history(atlas, commits=120, start=now - timedelta(days=95), last=now - timedelta(hours=6), rng=rng)
    for name, days_ago in [("feature/rate-limiting", 95), ("feature/audit-log", 120), ("bugfix/null-pointer", 88), ("release/1.2", 3)]:
        git(atlas, "checkout", "-b", name, "main")
        base = now - timedelta(days=days_ago)
        write_file(atlas, f"docs/{name.replace('/', '-')}.md", f"# {name}\n")
        commit(atlas, f"docs: start {name}", base, AUTHORS[1])
        git(atlas, "checkout", "main")
    git(atlas, "checkout", "-b", "develop", "main")
    write_file(atlas, "docs/develop.md", "# develop branch\n")
    commit(atlas, "chore: create develop branch", now - timedelta(days=20), AUTHORS[2])
    git(atlas, "checkout", "main")
    git(atlas, "merge", "--no-ff", "-m", "chore: merge feature/audit-log", "feature/audit-log", check=False)
    created.append(atlas)

    # 2. second active repository
    if count > 1 and (nebula := prepare("nebula-web")):
        build_history(nebula, commits=70, start=now - timedelta(days=70), last=now - timedelta(days=1), rng=rng)
        git(nebula, "branch", "feature/dark-mode")
        created.append(nebula)

    # 3. stale repository (last commit ~140 days ago) with stale branches
    if count > 2 and (legacy := prepare("legacy-billing")):
        build_history(legacy, commits=140, start=now - timedelta(days=900), last=now - timedelta(days=140), rng=rng)
        for name in ["feature/soap-api", "feature/pdf-invoices", "hotfix/vat-rounding", "refactor/money-type"]:
            git(legacy, "branch", name)
        created.append(legacy)

    # 4. abandoned candidate (last commit ~400 days ago)
    if count > 3 and (side := prepare("side-experiment")):
        build_history(side, commits=18, start=now - timedelta(days=460), last=now - timedelta(days=400), rng=rng)
        created.append(side)

    # 5. dirty working tree: staged, modified and untracked files
    if count > 4 and (infra := prepare("infra-scripts")):
        build_history(infra, commits=40, start=now - timedelta(days=200), last=now - timedelta(days=5), rng=rng)
        write_file(infra, "src/deploy.py", "# modified but not committed\nprint('deploy')\n")
        write_file(infra, "src/staged_change.py", "# staged change\n")
        write_file(infra, "notes.txt", "untracked scratch notes\n")
        write_file(infra, "tmp/debug.log", "untracked log file\n")
        git(infra, "add", "src/staged_change.py")
        created.append(infra)

    # 6. detached HEAD
    if count > 5 and (detached := prepare("detached-sandbox")):
        build_history(detached, commits=25, start=now - timedelta(days=150), last=now - timedelta(days=30), rng=rng)
        head = git(detached, "rev-parse", "HEAD~2").stdout.strip()
        git(detached, "checkout", "--detach", head)
        created.append(detached)

    # 7. repository without commits
    if count > 6 and (empty := prepare("empty-project")):
        write_file(empty, "README.md", "# empty-project\n\nNo commits yet.\n")
        created.append(empty)

    # 8. bare mirror
    if count > 7:
        mirror = target / "mirror.git"
        if mirror.exists():
            print(f"  · {mirror} already exists, skipping")
        else:
            git(target, "clone", "--bare", str(atlas), str(mirror))
            created.append(mirror)

    return created


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Create demo Git repositories for the dashboard.")
    parser.add_argument("--target", default="data/demo", help="Directory that will hold the demo repositories")
    parser.add_argument("--repos", type=int, default=8, help="How many demo repositories to create (max 8)")
    parser.add_argument("--seed", type=int, default=1337, help="Random seed for reproducible histories")
    args = parser.parse_args(argv)

    target = Path(args.target).expanduser().resolve()
    print(f"Creating up to {min(args.repos, 8)} demo repositories in {target}")
    created = demo_repositories(target, count=min(args.repos, 8), seed=args.seed)
    if not created:
        print("Nothing created (the target directory already contains demo repositories).")
    for path in created:
        print(f"  ✓ {path}")
    print(
        "\nNext steps:\n"
        f'  1. python -m app discover "{target}" --register\n'
        "  2. python -m app scan --all\n"
        "  3. python -m app start"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
